x=int(input('enter first number -  '))
y=int(input('enter second number - '))
z=(input('enter your opertor - '))
if(z=='+') : print('your result is',x+y)
elif(z=='-') : print('your result is',x-y)
elif(z=='*') : print('your result is',x*y)
else : print('your result is',x/y)
